using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunkai.Parsers
{
    internal static class RegionMap
    {
        public readonly static ImmutableDictionary<string, Region> NOINTRO_MAP = new Dictionary<string, Region>() {
            { "Australia" , Region.Australia},
            { "Argentina" , Region.Argentina},
            { "Brazil" , Region.Brazil},
            { "Canada" , Region.Canada},
            { "China" , Region.China},
            { "Denmark" , Region.Denmark},
            { "Netherlands" , Region.Netherlands},
            { "Europe" , Region.Europe},
            { "France" , Region.France},
            { "Germany" , Region.Germany},
            { "Greece" , Region.Greece},
            { "Hong Kong" , Region.HongKong},
            { "Italy" , Region.Italy},
            { "Japan" , Region.Japan},
            { "Korea" , Region.SouthKorea},
            { "Norway" , Region.Norway},
            { "Russia" , Region.Russia},
            { "Spain" , Region.Spain},
            { "Sweden" , Region.Sweden},
            { "USA" , Region.UnitedStates},
            { "UK" , Region.UnitedKingdom},
            { "United Kingdom" , Region.UnitedKingdom},
            { "Asia" , Region.Asia},
            { "Poland" , Region.Poland},
            { "Portugal" , Region.Portugal},
            { "Ireland" , Region.Ireland},
            { "Unknown" , Region.Unknown},
            { "Taiwan" , Region.Taiwan},
            { "Finland" , Region.Finland},
            { "UAE" , Region.UnitedArabEmirates},
            { "Albania" , Region.Albania},
            { "Austria" , Region.Austria},
            { "Bosnia" , Region.Bosnia},
            { "Belgium" , Region.Belgium},
            { "Bulgaria" , Region.Bulgaria},
            { "Switzerland" , Region.Switzerland},
            { "Chile" , Region.Chile},
            { "Serbia" , Region.Serbia},
            { "Cyprus" , Region.Cyprus},
            { "Czech Republic" , Region.Czechia},
            { "Czechia" , Region.Czechia},
            { "Estonia" , Region.Estonia},
            { "Egypt" , Region.Egypt},
            { "Croatia" , Region.Croatia},
            { "Hungary" , Region.Hungary},
            { "Indonesia" , Region.Indonesia},
            { "Israel" , Region.Israel},
            { "India" , Region.India},
            { "Iran" , Region.Iran},
            { "Iceland" , Region.Iceland},
            { "Jordan" , Region.Jordan},
            { "Lithuania" , Region.Lithuania},
            { "Luxembourg" , Region.Luxembourg},
            { "Latvia" , Region.Latvia},
            { "Mongolia" , Region.Mongolia},
            { "Mexico" , Region.Mexico},
            { "Malaysia" , Region.Malaysia},
            { "Nepal" , Region.Nepal},
            { "New Zealand" , Region.NewZealand},
            { "Oman" , Region.Oman},
            { "Peru" , Region.Peru},
            { "Philippines" , Region.Philippines},
            { "Qatar" , Region.Qatar},
            { "Romania" , Region.Romania},
            { "Singapore" , Region.Singapore},
            { "Slovenia" , Region.Slovenia},
            { "Slovakia" , Region.Slovakia},
            { "Thailand" , Region.Thailand},
            { "Turkey" , Region.Turkey},
            { "Vietnam" , Region.Vietnam},
            { "Yugoslavia" , Region.Yugoslavia},
            { "South Africa" , Region.SouthAfrica},
            { "The Netherlands" , Region.Netherlands},
            }.ToImmutableDictionary();


        public static readonly ImmutableArray<Region> WORLD = ImmutableArray.Create(Region.UnitedStates, Region.Japan, Region.Europe);
        public static readonly ImmutableArray<Region> SCANDINAVIA = ImmutableArray.Create(Region.Denmark, Region.Norway, Region.Sweden);
        public static readonly ImmutableArray<Region> LATIN_AMERICA = ImmutableArray.Create(Region.Mexico, Region.Brazil, Region.Argentina, Region.Chile, Region.Peru);


        public static readonly ImmutableDictionary<string, Language> LANGUAGE_MAP = new Dictionary<string, Language>()
        {
            {"ab", Language.Abkhaz},
            {"aa", Language.Afar},
            {"af", Language.Afrikaans},
            {"ak", Language.Akan},
            {"sq", Language.Albanian},
            {"am", Language.Amharic},
            {"ar", Language.Arabic},
            {"an", Language.Aragonese},
            {"hy", Language.Armenian},
            {"as", Language.Assamese},
            {"av", Language.Avaric},
            {"ae", Language.Avestan},
            {"ay", Language.Aymara},
            {"az", Language.Azerbaijani},
            {"bm", Language.Bambara},
            {"ba", Language.Bashkir},
            {"eu", Language.Basque},
            {"be", Language.Belarusian},
            {"bn", Language.Bengali},
            {"bh", Language.Bihari},
            {"bi", Language.Bislama},
            {"bs", Language.Bosnian},
            {"br", Language.Breton},
            {"bg", Language.Bulgarian},
            {"my", Language.Burmese},
            {"ca", Language.Catalan},
            {"ch", Language.Chamorro},
            {"ce", Language.Chechen},
            {"ny", Language.Nyanja},
            {"zh", Language.Chinese},
            {"cv", Language.Chuvash},
            {"kw", Language.Cornish},
            {"co", Language.Corsican},
            {"cr", Language.Cree},
            {"hr", Language.Croatian},
            {"cs", Language.Czech},
            {"da", Language.Danish},
            {"dv", Language.Maldivian},
            {"nl", Language.Dutch},
            {"dz", Language.Dzongkha},
            {"en", Language.English},
            {"eo", Language.Esperanto},
            {"et", Language.Estonian},
            {"ee", Language.Ewe},
            {"fo", Language.Faroese},
            {"fj", Language.Fijian},
            {"fi", Language.Finnish},
            {"fr", Language.French},
            {"ff", Language.Pular},
            {"gl", Language.Galician},
            {"ka", Language.Georgian},
            {"de", Language.German},
            {"el", Language.Greek},
            {"gn", Language.Guaraní},
            {"gu", Language.Gujarati},
            {"ht", Language.Haitian},
            {"ha", Language.Hausa},
            {"he", Language.Hebrew},
            {"hz", Language.Herero},
            {"hi", Language.Hindi},
            {"ho", Language.HiriMotu},
            {"hu", Language.Hungarian},
            {"ia", Language.Interlingua},
            {"id", Language.Indonesian},
            {"ie", Language.Interlingue},
            {"ga", Language.Irish},
            {"ig", Language.Igbo},
            {"ik", Language.Inupiaq},
            {"io", Language.Ido},
            {"is", Language.Icelandic},
            {"it", Language.Italian},
            {"iu", Language.Inuktitut},
            {"ja", Language.Japanese},
            {"jv", Language.Javanese},
            {"kl", Language.Greenlandic},
            {"kn", Language.Kannada},
            {"kr", Language.Kanuri},
            {"ks", Language.Kashmiri},
            {"kk", Language.Kazakh},
            {"km", Language.Khmer},
            {"ki", Language.Kikuyu},
            {"rw", Language.Kinyarwanda},
            {"ky", Language.Kyrgyz},
            {"kv", Language.Komi},
            {"kg", Language.Kongo},
            {"ko", Language.Korean},
            {"ku", Language.Kurdish},
            {"kj", Language.Kwanyama},
            {"la", Language.Latin},
            {"lb", Language.Luxembourgish},
            {"lg", Language.Ganda},
            {"li", Language.Limburgish},
            {"ln", Language.Lingala},
            {"lo", Language.Lao},
            {"lt", Language.Lithuanian},
            {"lu", Language.LubaKatanga},
            {"lv", Language.Latvian},
            {"gv", Language.Manx},
            {"mk", Language.Macedonian},
            {"mg", Language.Malagasy},
            {"ms", Language.Malay},
            {"ml", Language.Malayalam},
            {"mt", Language.Maltese},
            {"mi", Language.Maori},
            {"mr", Language.Marathi},
            {"mh", Language.Marshallese},
            {"mn", Language.Mongolian},
            {"na", Language.Nauru},
            {"nv", Language.Navajo},
            {"nb", Language.Bokmal},
            {"nd", Language.Ndebele},
            {"ne", Language.Nepali},
            {"ng", Language.Ndonga},
            {"nn", Language.Nynorsk},
            {"no", Language.Norwegian},
            {"ii", Language.Nuosu},
            {"nr", Language.SouthNdebele},
            {"oc", Language.Occitan},
            {"oj", Language.Ojibwe},
            {"cu", Language.Slavonic},
            {"om", Language.Oromo},
            {"or", Language.Oriya},
            {"os", Language.Ossetian},
            {"pa", Language.Punjabi},
            {"pi", Language.Pali},
            {"fa", Language.Farsi},
            {"pl", Language.Polish},
            {"ps", Language.Pashto},
            {"pt", Language.Portuguese},
            {"qu", Language.Quechua},
            {"rm", Language.Romansh},
            {"rn", Language.Kirundi},
            {"ro", Language.Romanian},
            {"ru", Language.Russian},
            {"sa", Language.Sanskrit},
            {"sc", Language.Sardinian},
            {"sd", Language.Sindhi},
            {"se", Language.Sami},
            {"sm", Language.Samoan},
            {"sg", Language.Sango},
            {"sr", Language.Serbian},
            {"gd", Language.Gaelic},
            {"sn", Language.Shona},
            {"si", Language.Sinhalese},
            {"sk", Language.Slovak},
            {"sl", Language.Slovene},
            {"so", Language.Somali},
            {"st", Language.Sotho},
            {"es", Language.Spanish},
            {"su", Language.Sundanese},
            {"sw", Language.Swahili},
            {"ss", Language.Swati},
            {"sv", Language.Swedish},
            {"ta", Language.Tamil},
            {"te", Language.Telugu},
            {"tg", Language.Tajik},
            {"th", Language.Thai},
            {"ti", Language.Tigrinya},
            {"bo", Language.Tibetan},
            {"tk", Language.Turkmen},
            {"tl", Language.Tagalog},
            {"tn", Language.Tswana},
            {"to", Language.Tonga},
            {"tr", Language.Turkish},
            {"ts", Language.Tsonga},
            {"tt", Language.Tatar},
            {"tw", Language.Twi},
            {"ty", Language.Tahitian},
            {"ug", Language.Uyghur},
            {"uk", Language.Ukrainian},
            {"ur", Language.Urdu},
            {"uz", Language.Uzbek},
            {"ve", Language.Venda},
            {"vi", Language.Vietnamese},
            {"vo", Language.Volapük},
            {"wa", Language.Walloon},
            {"cy", Language.Welsh},
            {"wo", Language.Wolof},
            {"fy", Language.Frisian},
            {"xh", Language.Xhosa},
            {"yi", Language.Yiddish},
            {"yo", Language.Yoruba},
            {"za", Language.Zhuang},
            {"zu", Language.Zulu}
        }.ToImmutableDictionary();
    }
}
